### PR TITLE
prevent auth form from reloading the page

### LINKED ISSUE #21: Login and Register both fail the first time
Including both the live demo and my local cloned project, every single time you try to login and register with valid credentials, it silently fails (without any errors). The second or third time,  etc.,  it works.

I suppose the problem lies somewhere in the vuex implementation.

### PR DESCRIPTION
**Pull request by vilsbole**
closes #21

### CODE REVIEW

File: src/views/Login.vue [hunk 1]
```diff
@@ -54,6 +54,7 @@ export default {
   },
   methods: {
     onSubmit (email, password) {
+      console.log('submit form')
```
Comment (igeligel) [inline src/views/Login.vue]: I think we should delete the logging statements here.

Comment (vilsbole) [reply src/views/Login.vue]: Yes certainly!
